name: Codestyle
on:
  pull_request:
    paths-ignore:
      - docs/**
      - README.md
      - README_PYPI.md
      - cli/**
      - examples/**
      - images/**
      - .gitignore
      - COPYING
      - build.*
      - pull_datasets.sh
      - pyproject.toml
  push:
    branches:
      - add_clang_tidy
    paths-ignore:
      - docs/**
      - README.md
      - README_PYPI.md
      - cli/**
      - examples/**
      - images/**
      - .gitignore
      - COPYING
      - build.*
      - pull_datasets.sh
      - pyproject.toml

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  # Cancel in-progress runs when a new workflow with the same group name is triggered
  cancel-in-progress: true

jobs:
  clang-format-check:
    continue-on-error: true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install clang-format
        run: |
          sudo add-apt-repository 'deb http://apt.llvm.org/jammy/ llvm-toolchain-jammy-18 main'
          wget https://apt.llvm.org/llvm-snapshot.gpg.key
          sudo apt-key add llvm-snapshot.gpg.key
          sudo apt-get update
          sudo apt-get install -y clang-format-18

      - name: Check formatting
        run: |
          set +e
          formatterOutput=$(git diff -U0 origin/$GITHUB_BASE_REF...HEAD | clang-format-diff-18 -p 1)

          if [ "$formatterOutput" != "" ]
          then
            echo ":x: :x: :x:" >> $GITHUB_STEP_SUMMARY
            echo "\`\`\`c++" >> $GITHUB_STEP_SUMMARY
            echo "$formatterOutput" >> $GITHUB_STEP_SUMMARY
            echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
            echo "$formatterOutput"
            exit 1
          fi

          echo "$formatterOutput"
          echo "### $formatterOutput :heavy_check_mark:" >> $GITHUB_STEP_SUMMARY

  clang-tidy-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        uses: ./.github/composite-actions/install-dependencies
        with:
          os: ubuntu
          toolset: gcc
          download-pybind: true

      - name: Generate compile_commands.json
        run: |
          cmake -DCMAKE_CXX_COMPILER=g++-10 \
            -DCMAKE_BUILD_TYPE=Debug \
            -Dgtest_disable_pthreads=OFF \
            -DASAN=OFF \
            -DPYTHON=COMPILE \
            -DCMAKE_EXPORT_COMPILE_COMMANDS=ON \
            -S . -B ${{github.workspace}}/build

      - name: Try ZedThree/clang-tidy-review
        id: clang-tidy-review
        continue-on-error: true
        uses: ZedThree/clang-tidy-review@v0.19.0
        with:
          apt_packages: libboost-dev
          build_dir: build
          config_file: '.clang-tidy'
          split_workflow: true

      - name: Check if error is due to too many files
        id: check-error
        if: steps.clang-tidy-review.outcome == 'failure'
        run: |
          if grep -q "diff exceeded the maximum number of files" <<< "${{ steps.clang-tidy-review.outputs.error }}"; then
            echo "error_type=too_many_files" >> $GITHUB_OUTPUT
          else
            echo "error_type=other" >> $GITHUB_OUTPUT
          fi

      - name: Set error type variable
        id: set-error-type
        run: |
          echo "error_type=${{ steps.check-error.outputs.error_type }}" >> $GITHUB_ENV

      - name: Install clang-tidy
        if: env.error_type == 'too_many_files'
        run: |
          sudo add-apt-repository 'deb http://apt.llvm.org/jammy/ llvm-toolchain-jammy-19 main'
          wget https://apt.llvm.org/llvm-snapshot.gpg.key
          sudo apt-key add llvm-snapshot.gpg.key
          sudo apt-get update
          sudo apt-get install -y clang-tidy-19

      - name: Fallback to local git diff if too many files
        if: env.error_type == 'too_many_files'
        id: changed-files
        run: |
          git fetch origin $GITHUB_BASE_REF
          echo "changed_files=$(git diff -U0 origin/$GITHUB_BASE_REF...HEAD | grep -E '\.(h|cpp)$' | tr '\n' ' ')" >> $GITHUB_OUTPUT

      - name: Run clang-tidy on changed files (fallback)
        if: env.error_type == 'too_many_files'
        run: |
          echo "Changed files: ${{ steps.changed-files.outputs.changed_files }}"
          if [ -n "${{ steps.changed-files.outputs.changed_files }}" ]; then
            clang-tidy -p build ${{ steps.changed-files.outputs.changed_files }}
          else
            echo "No changed files to check."
          fi

      - name: Upload clang-tidy results
        if: env.error_type != 'too_many_files'
        uses: ZedThree/clang-tidy-review/upload@v0.19.0

      - name: Fail the check if clang-tidy reported issues
        if: failure()
        run: exit 1
